---
- name: "deploy-backend play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml


  roles:
    - deploy

  environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: postgres
      TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
      TYPEORM_HOST: database-2.cdh9tqqgjmpg.us-west-2.rds.amazonaws.com
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: postgres321
      TYPEORM_PASSWORD: postgres123
      TYPEORM_DATABASE: databaseu
